# Generated by Django 3.2.23 on 2024-02-02 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskMonitorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=128, verbose_name='任务名称')),
                ('job_id', models.CharField(max_length=128, verbose_name='任务id')),
                ('state', models.CharField(max_length=128, verbose_name='任务运行状态')),
                ('last_cnt', models.BigIntegerField(verbose_name='上次同步数量')),
                ('failed_cnt', models.IntegerField(verbose_name='失败计数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('del_flag', models.SmallIntegerField(default=0, verbose_name='删除标记')),
                ('inc_cnt', models.IntegerField(default=0, verbose_name='本次同步增加数量')),
            ],
            options={
                'verbose_name': '任务监控记录',
                'verbose_name_plural': '任务监控记录',
                'db_table': 'task_monitor_log',
            },
        ),
        migrations.CreateModel(
            name='MonitorHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor_time', models.DateTimeField(auto_now_add=True, verbose_name='监控时间')),
                ('exception_detail', models.CharField(max_length=256, verbose_name='异常信息')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.taskmonitorlog', verbose_name='任务id')),
            ],
        ),
    ]
