# Generated by Django 3.2.23 on 2024-02-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=128, verbose_name='视频名称')),
                ('aid', models.BigIntegerField(verbose_name='视频aid')),
                ('bvid', models.BigIntegerField(verbose_name='视频bvid')),
                ('way', models.SmallIntegerField(choices=[(0, 'watch'), (1, 'like'), (2, 'dislike'), (3, 'share')], verbose_name='视频获取方式 0指定视频类型 1首页推荐')),
                ('action', models.SmallIntegerField(choices=[(0, 'watch'), (1, 'like'), (2, 'dislike'), (3, 'share')], verbose_name='操作 0,观看 1,点赞 2,取消点赞 3,分享')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('del_flag', models.SmallIntegerField(default=0, verbose_name='删除标记')),
            ],
            options={
                'verbose_name': 'bili 事件记录',
                'verbose_name_plural': 'bili 事件记录',
                'db_table': 'bili_action_record',
            },
        ),
        migrations.CreateModel(
            name='ExpRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=128, verbose_name='用户名称')),
                ('uid', models.BigIntegerField(verbose_name='用户UID')),
                ('current_exp', models.IntegerField(verbose_name='当前经验值')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('del_flag', models.SmallIntegerField(default=0, verbose_name='删除标记')),
            ],
            options={
                'verbose_name': '经验值记录',
                'verbose_name_plural': '经验值记录',
                'db_table': 'bili_exp_record',
            },
        ),
    ]
