# Generated by Django 3.2.23 on 2024-02-02 23:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_actionrecord_bvid'),
    ]

    operations = [
        migrations.AddField(
            model_name='exprecord',
            name='record_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, unique=True, verbose_name='记录日期'),
            preserve_default=False,
        ),
    ]
