# Generated by Django 3.2.23 on 2024-02-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_exprecord_record_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='exprecord',
            name='coins',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='硬币数'),
            preserve_default=False,
        ),
    ]
